### ISSUE TITLE
Установка v0.0.9.2.2 на Android (Termux) (только РУТ)

### ISSUE THREAD

**Issue by thereedlegend** [Woopertail/FunPayCardinal#1]
# Установка v0.0.9.2.2 на Android (Termux) (только РУТ):
### 1. Обновляем системные пакеты
```
pkg upgrade
```
### 2. 
```
pkg install tsu
```
### 3. Устанавливаем python
```
pkg install python
```
### 4. Переносим папку с ботом по пути 
```/data/data/com.termux/files/home/```
### 5. 
```
cd "имя вашей папки"
```
### 6. 
```
python3.11 setup.py
```
### Примечание:
Желательно не выполнять полную установку setup.py от имени суперпользователя, т.е.
```
sudo python3.11 setup.py
```
так как это приводит к бутлупу вашего устройства. 
### 7. 
В процессе установки могут возникнуть (у меня возникают) ошибки с установкой Pillow, Telebot (игнорируем).
### 8. 
Теперь необходимо установить Pillow без ошибок с помощью команд: 
а) 
``` 
pkg install libjpeg-turbo
```
б) 
```
LDFLAGS="-L/system/lib/" CFLAGS="-I/data/data/com.termux/files/usr/include/" pip install Pillow
```
### Примечание 1: 
Если вы используете aarch64 устройство (arm64), установите в LDFLAGS флаг на "-L/system/lib64/" т.е. команда будет выглядеть так 
```
LDFLAGS="-L/system/lib64/" CFLAGS="-I/data/data/com.termux/files/usr/include/" pip install Pillow
```
### Примечание 2: 
Если после ввода команды собрать Pillow всё также не получается, необходимо выполнить команду от суперпользователя: 
```
sudo LDFLAGS="-L/system/lib/" CFLAGS="-I/data/data/com.termux/files/usr/include/" pip install Pillow
```
### 9. 
```
pip3 install telebot
``` 
### Примечание 1: 
Если после ввода команды установить telebot всё также не получается, необходимо выполнить команду от суперпользователя: 
```
sudo pip3 install telebot
``` 
### 10. 
После успешной установки мы можем попробовать запустить main.py
```
python3.11 main.py
```
Если не запускается:
```
sudo python3.11 main.py
```

### ГОТОВО
Надеюсь, всем смог помочь (ИНСТРУКЦИЯ РАБОТАЕТ КОРРЕКТНО ТОЛЬКО ДЛЯ v0.0.9.2.2, ИСПОЛЬЗУЙТЕ ЕЁ, ПОСКОЛЬКУ ДЛЯ БОЛЕЕ СТАРЫХ ВЕРСИЙ НУЖНО ИСПОЛЬЗОВАТЬ ДРУГИЕ КОМАНДЫ)

**Comment by Woopertail** [comment]
Добавлю в инструкцию в ближайшем времени, пасеба :)
